Repository scherermichael-oss/semvertest, pull requests merged in 2018-08, with the labels that each got.

#5 feat: Update README.md
  README.md
Labels: release/major

#6 fix: Update README.md
  README.md
Labels: release/minor

#8 fix: Update README.md
  README.md
Labels: release/patch

#12 feat(test): Update README.md
  README.md
Labels: release/minor

#13 fix: Update README.md.
  README.md
Labels: release/major

#15 feat: Update README.md
  README.md
Labels: release/minor

#16 chore: Update dependencies
  package-lock.json
  package.json
Labels: release/patch

#17 fix: Tests
  .circleci/config.yml
  CHANGELOG.md
  package.json
  roboter.js
  test/mocha.opts
  test/units/indexTests.js
Labels: release/patch

#18 feat: Build changelog.
  package-lock.json
  package.json
Labels: release/minor

#19 fix: Update README.md
  README.md
Labels: release/patch

#14 fix: Update README.md
  README.md
Labels: release/major

#20 feat: Update README.md
  README.md
Labels: release/major

#22 feat: Update README.md
  README.md
Labels: release/major

#23 fix: Update README.md
  README.md
Labels: release/major

#24 feat: Update README.md
  README.md
Labels: release/major

#26 fix: Update README.md
  README.md
Labels: release/major

#27 fix: Update README.md
  README.md
Labels: release/patch

#29 feat: Update README.md
  README.md
Labels: release/major

#28 feat: Update README.md
  README.md
Labels: release/minor

#30 fix: Update README.md
  README.md
Labels: release/major

#31 fix: Update README.md
  README.md
Labels: release/patch

#32 fix: Update README.md
  README.md
Labels: release/major

#34 feat: Issue references
  README.md
Labels: release/minor
